Fix gerrit_add_repo

diff --git a/gerrit_add_repo b/gerrit_add_repo
--- a/gerrit_add_repo
+++ b/gerrit_add_repo
@@ -14,13 +14,19 @@ fi
 
 case "${REPO_URI}" in
      *github*)
-        HOSTER=github.com
+        HOSTER=github
      ;;
      *gitorious*)
-        HOSTER=gitorious.org
+        HOSTER=gitorious
      ;;
      *git.exherbo.org*)
 	HOSTER=Exherbo
+     ;;
+     *thwitt.de*)
+	HOSTER=thwitt
+     ;;
+     *shadowice.org*)
+	HOSTER=thwitt
      ;;
      *)
         echo "Unknown hoster"
@@ -29,15 +35,14 @@ case "${REPO_URI}" in
 esac
 
 case "${REPO_URI}" in
-     *git.exherbo.org/*)
-        REPLICATION_GROUP=official
-     ;;
      *git.exherbo.org/dev/*)
         REPLICATION_GROUP=dev
      ;;
+     *git.exherbo.org/*)
+        REPLICATION_GROUP=official
+     ;;
      *)
-        echo "Unknown replication group"
-        exit 4
+        echo "Will generate a new replication group"
      ;;
 esac
 
@@ -58,17 +63,18 @@ if [[ -n $4 && -n $5 ]]; then
    REPO_OWNER_EMAIL=$5
 fi
 
+
 cd "${REPOPATH}"
 
-git clone --bare "${REPO_URI}" "${REPO_NAME}"
+git clone --bare "${REPO_URI}" "${REPO_NAME}".git
 
-if [[ ! -d ${REPOPATH}/${REPO_NAME} ]]; then
+if [[ ! -d ${REPOPATH}/${REPO_NAME}.git ]]; then
    echo "cloning failed"
    exit 2
 fi
 
-sudo chown -R ${USER}:${GROUP} "${REPO_NAME}"
-sudo chmod -R a+rwx "${REPO_NAME}"
+sudo chown -R ${USER}:${GROUP} "${REPO_NAME}.git"
+sudo chmod -R a+rwx "${REPO_NAME}.git"
 
 ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit flush-caches --cache project_list
 ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit set-project --submit-type REBASE_IF_NECESSARY --ps "${REPO_STATE}"  "${REPO_NAME}"
@@ -77,12 +83,17 @@ ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit flush-caches --cache project_list
 if [[ -z ${REPO_OWNER} ]]; then
    pushd /tmp
 
-   if [[ ! $(ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit ls-projects | grep "^${REPO_NAME//.git}$") ]]; then
+   if [[ ! $(ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit ls-projects | grep "^${REPO_NAME}$") ]]; then
       echo "repo not on Gerrit yet"
       sleep 1
       ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit flush-caches --cache project_list
       sleep 1
    fi   
+
+   if [[ ! $(ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit ls-projects | grep "^${REPO_NAME}$") ]]; then
+      echo "I FAILED"
+      exit 10
+   fi
 
    git clone "${GERRIT_SERVER}"/"${REPO_NAME}" "${REPO_NAME}"
    cd "${REPO_NAME}"
@@ -108,8 +119,8 @@ EOF
 
    popd
 
-   sudo chown -R ${USER}:${GROUP} "${REPO_NAME}"
-   sudo chmod -R a+rwx "${REPO_NAME}"
+   sudo chown -R ${USER}:${GROUP} "${REPO_NAME}.git"
+   sudo chmod -R a+rwx "${REPO_NAME}.git"
 
 elif [[ -n ${REPO_OWNER} ]]; then
    
@@ -123,14 +134,19 @@ elif [[ -n ${REPO_OWNER} ]]; then
 
    pushd /tmp
 
-   if [[ ! $(ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit ls-projects | grep "^${REPO_NAME//.git}$") ]]; then
+   if [[ ! $(ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit ls-projects | grep "^${REPO_NAME}$") ]]; then
       echo "repo not on Gerrit yet"
       sleep 1
       ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit flush-caches --cache project_list
       sleep 1
    fi
 
-   git clone "${REPO_URI}" "${REPO_NAME}"
+   if [[ ! $(ssh -p ${PORT} ${SSH_USER}@${SERVER} gerrit ls-projects | grep "^${REPO_NAME}$") ]]; then
+      echo "I FAILED"
+      exit 10
+   fi
+
+   git clone "${GERRIT_SERVER}"/"${REPO_NAME}" "${REPO_NAME}"
    cd "${REPO_NAME}"
    git fetch origin +refs/meta/*:refs/remotes/origin/*
    git checkout -b config --track origin/config
@@ -162,7 +178,7 @@ cat <<EOF > project.config
         publishDrafts = group ${REPO_OWNER}
 EOF
 
-   mysql -u ${MYSQL_USER} -p${MYSQL_PWD} ${MYSQL_DB} --skip-column-names -B -e "SELECT group_uuid, name FROM account_groups WHERE name in (\"Exherbo-${REPLICATION_GROUP}-replication\", \"${REPO_OWNER}\", \"Exherbo-${HOSTER}-${REPO_NAME}-replication\" )" >>groups
+   mysql -u ${MYSQL_USER} -p${MYSQL_PWD} ${MYSQL_DB} --skip-column-names -B -e "SELECT group_uuid, name FROM account_groups;" >>groups
 
    git add project.config groups
    git cm -m "Initial project config"
@@ -174,15 +190,15 @@ EOF
 
    popd
 
-   sudo chown -R ${USER}:${GROUP} "${REPO_NAME}"
-   sudo chmod -R a+rwx "${REPO_NAME}"
+   sudo chown -R ${USER}:${GROUP} "${REPO_NAME}.git"
+   sudo chmod -R a+rwx "${REPO_NAME}.git"
 
    pushd /var/cache/tomcat/gerrit/etc
 
    cat <<EOF > /tmp/replication.config
 # -----FIX THE URL LINE BELOW AND DELETE THIS LINE ------------
 [remote "Exherbo-${HOSTER}-${REPO_NAME}"]
-  url = git@${HOSTER}:${name}/${name}-exheres.git
+  url = git@${HOSTER}.com:${REPO_NAME}/\${name}-exheres.git
   push = refs/heads/*:refs/heads/*
   timeout = 15
   replicationDelay = 0
@@ -194,9 +210,9 @@ EOF
 
 EOF
 
-   cat /tmp/replication.config >>replication.config
-   emacs -nw replication.config
-
+   sudo cat /tmp/replication.config >>replication.config
+   sudo emacs -nw replication.config
+   
    # CAREFUL! The hostname in the next line MUST be "localhost"!
    ssh -p ${PORT} ${SSH_USER}@localhost gerrit plugin reload replication
 
@@ -207,28 +223,26 @@ fi
 
 # Add Jenkins task
 
+rm -rf /tmp/jenkins
 mkdir /tmp/jenkins
 pushd /tmp/jenkins
 wget https://${SERVER}/jenkins/jnlpJars/jenkins-cli.jar
 
 # The "philantrop" in the next line refers to the repository, not my nick. :-)
-java -jar jenkins-cli.jar -i ~/.ssh/id_dsa -s https://${SERVER}/jenkins/ copy-job philantrop ${REPO_NAME//.git}
-java -jar jenkins-cli.jar -s https://${SERVER}/jenkins/ get-job ${REPO_NAME//.git} > ${REPO_NAME//.git}.xml
-sed -i -e "s:philantrop:${REPO_NAME//.git}:g" ${REPO_NAME//.git}.xml
-java -jar jenkins-cli.jar -i ~/.ssh/id_dsa -s https://${SERVER}/jenkins/ update-job ${REPO_NAME//.git} < ${REPO_NAME//.git}.xml
+java -jar jenkins-cli.jar -i ~/.ssh/id_dsa -s https://${SERVER}/jenkins/ copy-job philantrop ${REPO_NAME}
+java -jar jenkins-cli.jar -s https://${SERVER}/jenkins/ get-job ${REPO_NAME} > ${REPO_NAME}.xml
+sed -i -e "s:philantrop:${REPO_NAME}:g" ${REPO_NAME}.xml
+java -jar jenkins-cli.jar -i ~/.ssh/id_dsa -s https://${SERVER}/jenkins/ update-job ${REPO_NAME} < ${REPO_NAME}.xml
+java -jar jenkins-cli.jar -s https://${SERVER}/jenkins/ build ${REPO_NAME}
 
 popd
 
-rm /tmp/jenkins
+rm -rf /tmp/jenkins
 
-systemd-nspawn --bind=/srv/www/localhost/htdocs/pbin:/var/db/paludis/repositories/pbin --bind-ro=/home/jenkins/workspace:/var/db/paludis/gerrit -D /srv/jenkins/amd64_base/amd64 -c "
-ln -s /etc/paludis/repositories/philantrop.bash /etc/paludis/repositories/${REPO_NAME//.git}.bash
-PALUDIS_DO_NOTHING_SANDBOXY=y cave search '*/*'
+sudo systemd-nspawn --bind=/srv/www/localhost/htdocs/pbin:/var/db/paludis/repositories/pbin --bind-ro=/home/jenkins/workspace:/var/db/paludis/gerrit -D /srv/jenkins/amd64_base/amd64 /bin/bash -c "
+chgrp tty /dev/tty
+source /etc/profile
 
-emacs /usr/local/bin/cave_install.bash
+ln -sf /etc/paludis/repositories/philantrop.bash /etc/paludis/repositories/${REPO_NAME}.bash
 "
-
-sudo cp /srv/jenkins/amd64_base/amd64/usr/local/bin/cave_install.bash /srv/tomcat/bin/
-
-emacs /srv/tomcat/bin/jenkins_build.bash
 
